version: '3'
services:
    # The ERP Container
    # -----------------
    # Accessing container via ssh: docker exec -u erp -it erp bash
    #
    erp:
      image:  partner.registry.abas.sh/abas/demo:2019r4n13
      container_name: "erp_importit2019"

      ports:
      - "${SSH_TEST_PORT:-2205}:22"
      - "${MINI_GUI_PORT:-8001}:80"
      - "${JAVA_DEBUG_PORT:-8017}:8017"
      - "${EDP_TEST_PORT:-6560}:6550"
      - "${GUI_TEST_PORT:-48592}:48392"

      environment:
      - ABAS_HOST=${ABAS_HOST}
      - ABAS_GUI_PORT=${GUI_TEST_PORT:-48592}

      # The hostname is very important, especially if you intend to use `docker commit`
      user: s3
      hostname: dockerbau
      command: /data/starteVersion.sh run

    # nexus for publishing abas Essentials libraries
    nexus:
      image: sonatype/nexus:oss
      container_name: "nexus"
      ports:
      - "8081:8081"
    sonaqube:
        image: sonarqube
        ports:
        - "19000:9000"
